[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "%mx*uAV@BAZ0dV@fORzw24^PLGRP@#CbDzDcT0Tm*Y61ZBti*r%xtr$3&67k!4$v"

[auth.auth0]
client_id = "o6oZyZwaS2SuQZqtlcHEqRNyMtzVCd6s"
client_secret = "n0BfhaiuxHx0Y_wQjFhAuSbsQ90DTfitrXjdvCHtt_c3EbQiLxZ7guLa-wi9ENZ0"
server_metadata_url = "https://dev-4n3ja4cmziu5xsvq.us.auth0.com/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" }